### PR TITLE
New Feature: Notification page

### PR DESCRIPTION
**Pull request by moex3**
This PR adds a notification page. These actions will show up on that page:
 - New comment on your crackme
 - Your crackme is uploaded and waiting approval
 - Your crackme is approved
 - Your crackme is rejected, with or without a reason
 - Your solution is waiting approval
 - Your solution is accepted
 - Your solution is rejected, with or without a reason
 - A new solution has been uploaded for your crackme

These notifications can also be deleted.
The rejection message can be specified with the delete.py script last, optional argument.

I tested this, but it should be tested again.

### CODE REVIEW

**Comment by sar5430** [comment]
Thanks for the PR ! I'll review it as soon as I can

**Review by sar5430 — COMMENTED** [review]
Hey ! I tested the implementation locally, but have a problem making it work. When I click on the notification button in the top bar, i've got the following template error : 

`Template Parse Error: template: notifs.tmpl:12: unexpected "=" in operand`

Do you have the same error ?

**Comment by sar5430** [comment]
Ok, my problem was that I was using a way to old version of go. I've downloaded the last version of go (1.16), but now the command `go get` wasn't working anymore. I find some time on internet and realized that the architecture of the project was really outdated (vendor/ folder is not used anymore). I've update the structure of the project in the following:  

- `vendor` directory has been removed. Now it's just `app` (`vendor/app -> app/`)
- all local dependencies changed in the import section at the beggining of each file (for example `app/controller` has been replaced to `github.com/sar5430/crackmes.one/app/controller`)

Can you please update this PR as well ? Sorry to bother you with that, I don't understand why this has to be changed ...

**Comment by moex3** [comment]
Thanks for updating the project. This explains why it was so painful to get the vendor directory working 😅 
I rebased the branch and renamed the imports. Should be good now.

**Comment by sar5430** [comment]
Great work, thanks a lot !

**Pull request merged**
